### ISSUE TITLE
System.IO.FileNotFoundException: Could not find file 'Sony - PlayStation 3 - Disc Keys (3684) (2022-10-17 02-43-20).zip'

### ISSUE THREAD

**Issue by matcarfer** [13xforever/ps3-disc-dumper#26]
Hello, I just started using PS3 Disc Dumper to dump my games, and looking at the log found:
System.IO.FileNotFoundException: Could not find file 'e:\TOOLS PORTABLE\ps3-disc-dumper\Sony - PlayStation 3 - Disc Keys (3684) (2022-10-17 02-43-20).zip'.
Im sure this isnt normal, any help?
Log attached.
[2022-10-16-2.log](https://github.com/13xforever/ps3-disc-dumper/files/9796519/2022-10-16-2.log)

**Comment by 13xforever** [comment]
It's a warning, not an error, and I'm pretty sure the keys are read in memory, this is only for persistent local cache storage to not look up from remote server every time.

**Comment by matcarfer** [comment]
Log says file not found despite that file IS downloaded by app, and correctly named and placed. My understanding is that app is not finding the zip file despite all being correct.

**Comment by 13xforever** [comment]
Looked at the code, and the only explanation for this issue is that something is deleting the file between directory enumeration and the attempt to open the file (probably antivirus).

In any case, as I said before, this is irrelevant because dumper will use the latest copy it downloaded from redump anyway.
