### ISSUE TITLE
Disc Dumping Error

### ISSUE THREAD

**Issue by tbrax15** [13xforever/ps3-disc-dumper#28]
![Screenshot 2022-11-26 111422](https://user-images.githubusercontent.com/119127543/204100870-ce909ab7-0054-41da-9c68-1778f6dc0103.png)

I am getting this error when trying to dump the disc.  Any suggestions?

**Comment by tbrax15** [comment]
I got the ird from this website: https://ps3.aldostools.org/ird.html

**Comment by 13xforever** [comment]
Please upload log. Also dumper will look for relevant ird automatically, you don't have to download anything.

**Comment by tbrax15** [comment]
What do you mean by upload log?

Thank you for the quick response.

**Comment by tbrax15** [comment]
Also, how to I not run it as an administrator?

**Comment by 13xforever** [comment]
This app doesn't require administrator privileges, _you_ made it run as an admin, so _you_ should know.

**Comment by tbrax15** [comment]
I clearly do not know what I am talking about. I am logged on as me, the only user, to my PC so naturally I have administrator privileges. 

I am asking how to fix this. I just need some help. I do not know what I am doing. And what does upload log mean?

**Comment by 13xforever** [comment]
I am sorry, but I'm not fixing issues with your system or your pc skill over github, you'll have to learn how to fix it yourself.

**Comment by maksg** [comment]
@13xforever I had the same issue just now but I figured out why it happens. It seems that if you open the exe via explorer without extracting the archive then the exe is in some Windows folder so it can't write data there. It would be nice if the app could detect if it's in such folder because some people may click on the exe since it's the single file in the archive.
